# ESP32-S3-Touch-LCD-7
substitutions:
  name: "display panel"
  friendly_name: "Display Panel"
  room: "Slaapkamer"
# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Packages
packages:
  setup:
    url: https://github.com/MrAtari1040ST/esphome-lvgl
    file: guition-esp32-s3-4848s040/package.yaml
    refresh: 1sec
